
package view;



import controller.DentistController;
import controller.UserController;
import model.Dentist;
import model.User;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Radil_Sanjuna
 */

public class DentistManagementForm extends javax.swing.JFrame {

   private DentistController dentistController;
    private UserController userController;
    
    
    public DentistManagementForm() {
   initComponents();

        setSize(1160, 780);
        setResizable(false);
        setLocationRelativeTo(null);

        dentistController = new DentistController();
        userController = new UserController();

        loadDentistUsers();
        loadDentistsToTable();
    }
    
    
    
private void loadDentistUsers() {

    cmbDentistUser.removeAllItems();
    cmbDentistUser.addItem("Select Dentist User");

    try {

        List<User> userList =
                userController.getDentistUsers();

        for (User user : userList) {

            String displayText =
                    user.getUserId()
                    + " - "
                    + user.getFullName()
                    + " ("
                    + user.getUsername()
                    + ")";

            cmbDentistUser.addItem(displayText);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading dentist users: "
                        + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    
private void clearFields() {

    txtDentistId.setText("");

    cmbDentistUser.setSelectedIndex(0);

    cmbSpecialization.setSelectedIndex(0);

    txtPhoneNumber.setText("");
}


 private void loadDentistsToTable() {

    DefaultTableModel tableModel =
            (DefaultTableModel) tblDentist.getModel();

    tableModel.setRowCount(0);

    try {

        List<Dentist> dentistList =
                dentistController.getAllDentists();

        for (Dentist dentist : dentistList) {

            Object[] rowData = {

                dentist.getDentistId(),
                dentist.getUserId(),
                dentist.getFullName(),
                dentist.getSpecialization(),
                dentist.getPhoneNumber()
            };

            tableModel.addRow(rowData);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading dentists: "
                        + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDentistId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cmbSpecialization = new javax.swing.JComboBox<>();
        txtPhoneNumber = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDentist = new javax.swing.JTable();
        cmbDentistUser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 780));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dentist Management ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(463, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1160, 70));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dentist ID :");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Select Dentist User :");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Specialization :");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Phone Number :");

        txtDentistId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDentistIdActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cmbSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Specialization", "General Dentistry                              ", "Orthodontics (Braces)                          ", "Periodontics (Gum Treatment)                  ", "Endodontics (Root Canal)                       ", "Pediatric Dentistry" }));

        btnAdd.setText("Add Dentist ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblDentist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dentist ID", "User ID", "Full Name", "Specialization", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblDentist);

        cmbDentistUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Dentist Name" }));
        cmbDentistUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDentistUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(62, 62, 62)
                        .addComponent(btnUpdate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtDentistId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnSearch))
                            .addComponent(cmbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDelete)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addComponent(btnClear))
                            .addComponent(cmbDentistUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDentistId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDentistUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 1000, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDentistIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDentistIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDentistIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

   String selectedUser =
            cmbDentistUser.getSelectedItem().toString();

    String specialization =
            cmbSpecialization.getSelectedItem().toString();

    String phoneNumber =
            txtPhoneNumber.getText().trim();

    if (selectedUser.equals("Select Dentist User")) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a Dentist User."
        );

        return;
    }

    if (specialization.equals("Select Specialization")) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a specialization."
        );

        return;
    }

    if (phoneNumber.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter the phone number."
        );

        return;
    }

    if (!phoneNumber.matches("^0\\d{9}$")) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid 10-digit phone number."
        );

        return;
    }

    try {

        int userId =
                Integer.parseInt(
                        selectedUser.split(" - ")[0]
                );

        Dentist dentist =
                new Dentist(
                        0,
                        userId,
                        null,
                        specialization,
                        phoneNumber
                );

        boolean added =
                dentistController.addDentist(dentist);

        if (added) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist added successfully!"
            );

            clearFields();
            loadDentistsToTable();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to add dentist. "
                    + "This user may already have a dentist profile."
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid User ID."
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }
    
    }//GEN-LAST:event_btnAddActionPerformed

    
    
    
    
    
    
    
    
    
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

           String idText =
            txtDentistId.getText().trim();

    if (idText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a Dentist ID."
        );

        return;
    }

    try {

        int dentistId =
                Integer.parseInt(idText);

        Dentist dentist =
                dentistController.searchDentist(dentistId);

        if (dentist == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist not found."
            );

            return;
        }

        selectDentistUser(dentist.getUserId());

        cmbSpecialization.setSelectedItem(
                dentist.getSpecialization()
        );

        txtPhoneNumber.setText(
                dentist.getPhoneNumber()
        );

        JOptionPane.showMessageDialog(
                this,
                "Dentist found successfully."
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Dentist ID must be a valid number."
        );
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    
    


    
private void selectDentistUser(int userId) {

    for (int i = 0;
         i < cmbDentistUser.getItemCount();
         i++) {

        String item =
                cmbDentistUser.getItemAt(i);

        if (item.startsWith(userId + " - ")) {

            cmbDentistUser.setSelectedIndex(i);

            return;
        }
    }
}
     
  


    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    String idText =
            txtDentistId.getText().trim();

    if (idText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a Dentist ID."
        );

        return;
    }

    String specialization =
            cmbSpecialization.getSelectedItem().toString();

    String phoneNumber =
            txtPhoneNumber.getText().trim();

    if (specialization.equals("Select Specialization")) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a specialization."
        );

        return;
    }

    if (!phoneNumber.matches("^0\\d{9}$")) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid 10-digit phone number."
        );

        return;
    }

    try {

        int dentistId =
                Integer.parseInt(idText);

        Dentist dentist =
                dentistController.searchDentist(dentistId);

        if (dentist == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist not found."
            );

            return;
        }

        dentist.setSpecialization(
                specialization
        );

        dentist.setPhoneNumber(
                phoneNumber
        );

        boolean updated =
                dentistController.updateDentist(dentist);

        if (updated) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist updated successfully!"
            );

            clearFields();
            loadDentistsToTable();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update dentist."
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Dentist ID must be a valid number."
        );
    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    

    
    
    
    
    
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

   String idText =
            txtDentistId.getText().trim();

    if (idText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a Dentist ID."
        );

        return;
    }

    try {

        int dentistId =
                Integer.parseInt(idText);

        int confirm =
                JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to delete this Dentist?",
                        "Confirm Delete",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean deleted =
                dentistController.deleteDentist(
                        dentistId
                );

        if (deleted) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist deleted successfully!"
            );

            clearFields();
            loadDentistsToTable();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist not found."
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Dentist ID must be a valid number."
        );
    }
  
        }//GEN-LAST:event_btnDeleteActionPerformed

    
    
    
    private void cmbDentistUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDentistUserActionPerformed
  
    }//GEN-LAST:event_cmbDentistUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
 clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(DentistManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(DentistManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(DentistManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(DentistManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new DentistManagementForm().setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDentistUser;
    private javax.swing.JComboBox<String> cmbSpecialization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDentist;
    private javax.swing.JTextField txtDentistId;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
