/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import controller.BillController;
import model.Bill;
import javax.swing.JOptionPane;

import java.io.File;
import util.ReceiptPDF;
/**
 *
 * @author Radil_Sanjuna
 */
public class ViewBillingForm extends javax.swing.JFrame {

    private BillController billController;
    
    public ViewBillingForm() {
        initComponents();
        setSize(1160, 780);
        setResizable(false);
        setLocationRelativeTo(null);

        billController = new BillController();

        txtAppointmentNumber.setEditable(false);
        txtPatientName.setEditable(false);
        txtPhone.setEditable(false);
        txtDentist.setEditable(false);
        txtTreatment.setEditable(false);
        txtAppointmentDate.setEditable(false);
        txtAppointmentTime.setEditable(false);
        txtTreatmentCost.setEditable(false);
        txtConsultationFee.setEditable(false);
        txtTotal.setEditable(false);
        txtPaymentStatus.setEditable(false);
        txtBillDate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBillNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtAppointmentNumber = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDentist = new javax.swing.JTextField();
        txtTreatment = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        txtTreatmentCost = new javax.swing.JTextField();
        txtConsultationFee = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtPaymentStatus = new javax.swing.JTextField();
        btnPrintRecipt = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtBillDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 780));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("View Billing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(505, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Bill Number :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 6, 138, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Patient Name :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 116, 110, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Phone :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 156, 110, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Dentist :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 196, 80, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Treatment :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 236, 80, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Appoinment Date :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 276, 138, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Appoinment Time :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 316, 129, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText(" Treatment Cost:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 363, 129, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Consultation Fee: ");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 397, 129, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Total Amount :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 442, 119, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Bill Date :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 520, 119, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Appoinment No:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 78, 138, -1));
        jPanel3.add(txtBillNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 6, 154, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 6, -1, -1));
        jPanel3.add(txtAppointmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 76, 154, -1));
        jPanel3.add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 116, 154, -1));
        jPanel3.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 156, 154, -1));
        jPanel3.add(txtDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 196, 154, -1));
        jPanel3.add(txtTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 236, 154, -1));
        jPanel3.add(txtAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 276, 154, -1));
        jPanel3.add(txtAppointmentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 316, 154, -1));
        jPanel3.add(txtTreatmentCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 363, 154, -1));
        jPanel3.add(txtConsultationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 397, 154, -1));
        jPanel3.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 442, 154, -1));
        jPanel3.add(txtPaymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 482, 154, -1));

        btnPrintRecipt.setText("Print Receipt");
        btnPrintRecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReciptActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrintRecipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 560, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 560, -1, -1));

        btnBack.setText("Back");
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, -1, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("payment Status :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 482, 119, -1));
        jPanel3.add(txtBillDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 522, 154, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
    String billNumber =
            txtBillNumber.getText().trim();

    if (billNumber.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter bill number."
        );

        return;
    }

    try {

        Bill bill =
                billController.searchBill(billNumber);

        if (bill == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill not found."
            );

            clearFields();
            return;
        }

        txtAppointmentNumber.setText(
                bill.getAppointmentNumber()
        );

        txtPatientName.setText(
                bill.getPatientName()
        );

        txtPhone.setText(
                bill.getPhoneNumber()
        );

        txtDentist.setText(
                bill.getDentistName()
        );

        txtTreatment.setText(
                bill.getTreatmentName()
        );

        txtAppointmentDate.setText(
                bill.getAppointmentDate().toString()
        );

        txtAppointmentTime.setText(
                bill.getAppointmentTime()
        );

        txtTreatmentCost.setText(
                bill.getTreatmentCost().toString()
        );

        txtConsultationFee.setText(
                bill.getConsultationFee().toString()
        );

        txtTotal.setText(
                bill.getTotalAmount().toString()
        );

        txtPaymentStatus.setText(
                bill.getPaymentStatus()
        );

        txtBillDate.setText(
                bill.getBillDate().toString()
        );

        JOptionPane.showMessageDialog(
                this,
                "Bill found successfully."
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error searching bill: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPrintReciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReciptActionPerformed
          String billNumber =
            txtBillNumber.getText().trim();

    // Check whether a bill has been searched
    if (billNumber.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please search for a bill first."
        );

        return;
    }

    try {

        // Get the bill from database
        Bill bill =
                billController.searchBill(
                        billNumber
                );

        if (bill == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill not found."
            );

            return;
        }

        // Generate PDF receipt
        File pdfFile =
                ReceiptPDF.generateReceipt(bill);

        // Open the generated PDF
        java.awt.Desktop.getDesktop().open(pdfFile);

        JOptionPane.showMessageDialog(
                this,
                "Receipt generated successfully."
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error generating receipt: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnPrintReciptActionPerformed

    
    private void clearFields() {

    txtBillNumber.setText("");

    txtAppointmentNumber.setText("");
    txtPatientName.setText("");
    txtPhone.setText("");
    txtDentist.setText("");
    txtTreatment.setText("");
    txtAppointmentDate.setText("");
    txtAppointmentTime.setText("");
    txtTreatmentCost.setText("");
    txtConsultationFee.setText("");
    txtTotal.setText("");
    txtPaymentStatus.setText("");
    txtBillDate.setText("");
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBillingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrintRecipt;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentNumber;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtBillDate;
    private javax.swing.JTextField txtBillNumber;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtDentist;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPaymentStatus;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTreatment;
    private javax.swing.JTextField txtTreatmentCost;
    // End of variables declaration//GEN-END:variables
}
